### ISSUE TITLE
License incompatible with Apache 2.0

### ISSUE THREAD

**Issue by vemilyus** [savsgio/gotils#1]
Hi, 

the GPL is incompatible with the Apache 2.0 license. Having this library be licensed under GPL forces any other project that depends on it to also be licensed under GPL. This especially affects Atreugo which is licensed under Apache 2.0.

I would therefore recommend licensing this library under a non-copyleft license (like Apache 2.0 or any BSD style license) to prevent a licensing conflict and to make it possible to use this library in thusly licensed projects.

It's the opinion of this developer that copyleft licenses do have their place, but not in application development.

**Comment by savsgio** [comment]
Hi @vemilyus,

Thank you so much. I didn't realize when i changed the license in Atreugo.

I will change the license here 😉

**Comment by savsgio** [comment]
Done!
